---
driver:
  name: vagrant
  provider: libvirt

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[dmlb2000_distro::default]
    attributes:
